In [2]:
import pandas as pd

This code takes the json files and regenerates CSVs, while grabbing F_AREA and PLANAREA from segments.json

It is to help seed the data so the 'lock' functionality works.

In [11]:
dfSegsWithData = pd.read_json('../_site-art-of-forecasting/data/segments.json')
dfSegsWithData

           SEGID PLANAREA  SUBAREAID CO_NAME F_AREA
0     0006_141.0      MAG          1    Utah    MAG
1     0006_146.9      MAG          1    Utah    MAG
2     0006_149.9      MAG          1    Utah    MAG
3     0006_150.6      MAG          1    Utah    MAG
4     0006_152.6      MAG          1    Utah    MAG
...          ...      ...        ...     ...    ...
9278   UDOT_7090     UDOT          0  Tooele   UDOT
9279   UDOT_7091     UDOT          0  Tooele   UDOT
9280   UDOT_7092     UDOT          0  Tooele   UDOT
9281   UDOT_7093     UDOT          0  Tooele   UDOT
9282   UDOT_7094     UDOT          0  Tooele   UDOT

[9283 rows x 5 columns]

In [21]:
# convert csvs to jsons
#lstSegidFiles = ['model-forecasts', 'aadt', 'linear-forecasts', 'segments']
lstSegidFiles = ['model-forecasts']

for file in lstSegidFiles:
    # Read CSV file
    print(file)

    _df = pd.read_json('../_site-art-of-forecasting/data/' + file + '.json')

    columns_to_drop = ['PLANAREA', 'SUBAREAID', 'CO_NAME', 'F_AREA']

    # Use list comprehension to filter columns that exist in the DataFrame
    columns_to_drop = [col for col in columns_to_drop if col in _df.columns]

    # Now, safely drop these columns if they exist
    _df.drop(columns=columns_to_drop, inplace=True)

    _dfWithSegData = pd.merge(dfSegsWithData, _df, on='SEGID', how='left')

    _dfWithSegData.to_csv('../intermediate/' + file + '.csv')

model-forecasts